### ISSUE TITLE
Points counter lock

### ISSUE THREAD

**Issue by SuperQuentin** [twesterapp/twester#15]
## Prerequisites
-   [x] I am on the [latest](https://github.com/twesterapp/twester/releases/latest) Twester version
-   [x] I have searched the [issues](https://github.com/twesterapp/twester/issues) of this repo and believe that this is not a duplicate

-   **OS version and name**: Windows 11 21H2 and Windows 10 previously too 
-   **Twester version**:  1.0.2

## Issue

My counter is locked and doesn't want to increase and i haven't any log about collecting points.

![image](https://user-images.githubusercontent.com/36150436/137399611-19ccc26e-97bd-4399-ba9a-b5c43828938d.png)

**Comment by ceoshikhar** [comment]
So you are saying that both `time counter` and `points counter` both are stuck and not increasing. Did you restart Twester and start watching streamers again? If yes then this is a very weird bug. 

But I would say, your internet was disconnected and Twester couldn't connect back to Twitch servers. I have noticed this myself. The status of watching a streamer also stays the same.

**Comment by SuperQuentin** [comment]
I try to restart the app multiple times and start watching again but it isn't working and there is only the `points counter` who doesn't work.

I try to recconnect my account  twitch but it doesn't seem to work, i will just clear my files and reinstall the app.

![image](https://user-images.githubusercontent.com/36150436/137456584-9647cbf6-0e4c-48ff-8922-5ac46fbb2fa9.png)

**Comment by ceoshikhar** [comment]
After you reinstalled Twester, did everything reset to 0? Also, is it working fine now?

**Comment by SuperQuentin** [comment]
Finally i juste remove twester files in `C:\Users\User\AppData\Roaming\Twester` and it resets everything without a reinstall

**Comment by ceoshikhar** [comment]
So you are saying something was wrong with the app's stored state that caused the bug? You just deleted saved state and it worked fine?
