### ISSUE TITLE
Adding Features from Original Miner?

### ISSUE THREAD

**Issue by Der-Floh** [twesterapp/twester#18]
I just wanted to ask if you Plan on supporting and developing Twester further and adding some features of the twitch-channel-points-miner-v2 like betting and such things. 😄 

I also wanted to ask if I should tell you every Idea for improvements / enhancements I have or wether you first want to continue with what you have to do right now

**Comment by ceoshikhar** [comment]
I plan on making Twester better everyday. You are welcome to do what you can do to help with it. I try to spend couple of hours a week on Twester. Once again, you are welcome to create issues and I'll definitely do the best I can. I look forward to making Twester a good tool for you, myself and everyone else.
