### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by l29** [twesterapp/twester#65]
Hi, i get a error when i try to login in. I tried with multiple twitch accounts, Twester Version 1.1.0 & 1.2.0-beta and with different ips. Im on Windows 10.
![image](https://user-images.githubusercontent.com/83277314/192160594-b96bcaef-100b-45d7-a632-083ac824e91a.png)

**Comment by ceoshikhar** [comment]
Can you open console by pressing F12 / cmd  + shift + i / ctrl + shift + i and then select "console" take screenshot of what gets printed there when you click on "Login".

**Comment by l29** [comment]
It doesnt write anything in it when i press login. The error message already appears when I open the console
![image](https://user-images.githubusercontent.com/83277314/192161025-7bf3a52e-eccd-4755-acbc-74c8df6ab738.png)

**Comment by ceoshikhar** [comment]
Can you open up "network" tab and show the "response" of the request that gets called when you click the button? It should probably have a reason as to why the login failed.

**Comment by l29** [comment]
![image](https://user-images.githubusercontent.com/83277314/192547518-d2c77081-ee44-4375-9af8-cc70254a8883.png)

**Comment by ceoshikhar** [comment]
I have investigated a bit on this. I think Twitch has blocked the client ID we use for making the login request. At the moment I have no idea if I will be able to solve it. I'll update you if I figure out something.

For now, everyone else, don't logout!

<img width="531" alt="Screenshot 2022-09-27 at 9 06 29 PM" src="https://user-images.githubusercontent.com/62669971/192571119-ca4ac21e-0af3-4484-ae5e-cb0fef5917c5.png">

**Comment by ceoshikhar** [comment]
Apparently Twitch has added additional mechanism (integrity check) while making the API call for login, points for raids & bonuses. I don't know if these issues will be solvable or not. I will update if there is anything new. 

I am following https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/606 to see if the original author and his community can find a solution to this.

**Comment by Lucifer192192** [comment]
twitch add kasada captcha,
I can't even login on to Twitch from my browser

**Comment by maxcamorra** [comment]
Yes its because of the 2 factor authentication

**Comment by Ayinaki** [comment]
Is this now broken then till a fix is found?

**Comment by ceoshikhar** [comment]
> Is this now broken then till a fix is found?

Seems pretty unlikely that this will be fixed anytime soon.

**Comment by SpectorTM** [comment]
https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/

This fork seems to work
